name: USM-cfDNA
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - attr=2.5.1
  - binutils_impl_linux-64=2.39
  - binutils_linux-64=2.39
  - boltons=23.0.0
  - bowtie=1.3.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2026.1.4
  - certifi=2025.8.3
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - conda=25.7.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - cpp-expected=1.1.0
  - cryptography=42.0.5
  - distro=1.9.0
  - fmt=9.1.0
  - frozendict=2.4.2
  - gcc=9.5.0
  - gcc_impl_linux-64=9.5.0
  - gcc_linux-64=9.5.0
  - gxx=9.5.0
  - gxx_impl_linux-64=9.5.0
  - gxx_linux-64=9.5.0
  - hmmcopy=0.1.1
  - htslib=1.22
  - icu=75.1
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.39
  - libarchive=3.7.7
  - libblas=3.11.0
  - libboost=1.88.0
  - libcap=2.75
  - libcblas=3.11.0
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libfabric=2.2.0
  - libfabric1=2.2.0
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-devel_linux-64=9.5.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.11.0
  - liblightgbm=4.6.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpmix=5.0.8
  - libsanitizer=9.5.0
  - libsolv=0.7.33
  - libsqlite=3.45.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=9.5.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libudev1=257.7
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - lz4-c=1.10.0
  - lzo=2.10
  - menuinst=2.1.1
  - mpi=1.0
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openmpi=5.0.8
  - openssl=3.6.1
  - packaging=23.2
  - pandas=2.3.1
  - patsy=1.0.1
  - pcre2=10.45
  - perl=5.32.1
  - platformdirs=3.10.0
  - pluggy=1.6.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - rdma-core=57.0
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - samtools=1.22
  - scipy=1.13.1
  - setuptools=69.5.1
  - simdjson=3.10.1
  - six=1.17.0
  - spdlog=1.12.0
  - sqlite=3.45.2
  - statsmodels=0.14.5
  - sysroot_linux-64=2.17
  - tbb=2022.1.0
  - tk=8.6.13
  - tqdm=4.66.4
  - tzdata=2024a
  - ucc=1.4.4
  - ucx=1.18.1
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml-cpp=0.8.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip=25.1.1
  - pip:
      - absl-py==2.3.0
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - biopython==1.83
      - biotite==0.40.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - coloredlogs==15.0.1
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cppimport==22.8.2
      - cuda-bindings==12.9.0
      - cuda-python==12.9.0
      - cxxfilt==0.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - dm-tree==0.1.8
      - einops==0.6.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fair-esm==2.0.0
      - fairscale==0.4.13
      - fastparquet==2024.11.0
      - filelock==3.13.1
      - fire==0.7.0
      - flatbuffers==25.2.10
      - fonttools==4.58.5
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.73.0
      - h5py==3.14.0
      - hf-xet==1.1.4
      - hidet==0.6.0
      - hip-python-fork==6.3.3.540.31.1
      - hjson==3.1.0
      - huggingface-hub==0.33.0
      - humanfriendly==10.0
      - ihm==2.7
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - intervaltree==3.1.0
      - iopath==0.1.10
      - ipython==8.18.1
      - isal==1.7.2
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.3
      - kiwisolver==1.4.7
      - lark==1.2.2
      - lazy-loader==0.4
      - levenshtein==0.27.1
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - lmdb==1.6.2
      - mako==1.3.10
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-collections==0.1.1
      - modelcif==1.4
      - mpi4py==4.1.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.5.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - numpy==1.26.3
      - nvidia-ml-py==12.575.51
      - nvtx==0.2.12
      - omegaconf==2.3.0
      - onnx==1.18.0
      - onnx-simplifier==0.4.36
      - onnxruntime-gpu==1.16.3
      - opencv-python==4.11.0.86
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - portalocker==3.2.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pulp==3.2.1
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pybind11==2.13.6
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydssp==0.9.1
      - pyfaidx==0.8.1.4
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pysam==0.23.3
      - pytest==8.4.0
      - pyyaml==6.0.2
      - rapidfuzz==3.13.0
      - rdkit==2024.3.2
      - regex==2024.11.6
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - sentencepiece==0.1.99
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - tomlkit==0.13.3
      - traitlets==5.14.3
      - transformers==4.52.4
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - wandb==0.20.1
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - wget==3.2
      - whatshap==2.8
      - xgboost-cpu==2.1.4
      - xopen==2.0.2
      - yacs==0.1.8
      - yarl==1.20.1
      - zipp==3.23.0
      - zlib-ng==0.5.1